<paste log output from Kubernetes-mediated prediction, here>

$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "prediction-app" already exists
NAME             READY   STATUS    RESTARTS   AGE
prediction-app   1/1     Running   0          2m8s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

$ kubectl logs prediction-app
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 162-885-597
[2021-08-12 16:23:38,780] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-08-12 16:23:38,796] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-08-12 16:23:38,806] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-08-12 16:23:38,810] INFO in app: Output prediction value:
[20.35373177134412]
127.0.0.1 - - [12/Aug/2021 16:23:38] "POST /predict HTTP/1.1" 200 -